---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guotongning.
--- DateTime: 2021/5/11 7:03 下午
---
local arrayStr = "ohZfw1JWZZss37AXP1FPexe-Xm_11,1258874973636706304,575993868"
local flag = 1
local pattern = flag == 1 and "([%w_-]+),(%w+)" or "(%w+),(%w+)"
print("flag:" .. flag .. ", pattern:" .. pattern)
for k, v in string.gmatch(arrayStr, pattern) do
    print(k .. ":" .. v)
end

local key, value = string.match(arrayStr, pattern)
print(key .. ":" .. value)

local arr = { "a", "b", "c" }
for i, v in ipairs(arr) do
    print(i .. ":" .. v)
end

local str = "abcdefg"
local strBuilder = ""
for k in string.gmatch(str, "(%w)") do
    strBuilder = strBuilder .. k .. ","
end
strBuilder = string.sub(strBuilder, 0, #strBuilder - 1)
print(strBuilder)
